/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cruxic_aware_GLImage */

#ifndef _Included_cruxic_aware_GLImage
#define _Included_cruxic_aware_GLImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cruxic_aware_GLImage
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cruxic_aware_GLImage_dispose
  (JNIEnv *, jobject);

/*
 * Class:     cruxic_aware_GLImage
 * Method:    loadFromFile
 * Signature: (Ljava/lang/String;)Lcruxic/aware/GLImage;
 */
JNIEXPORT jobject JNICALL Java_cruxic_aware_GLImage_loadFromFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cruxic_aware_GLImage
 * Method:    readImageSize
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cruxic_aware_GLImage_readImageSize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cruxic_aware_GLImage
 * Method:    createFromRawBytes
 * Signature: (II[B)Lcruxic/aware/GLImage;
 */
JNIEXPORT jobject JNICALL Java_cruxic_aware_GLImage_createFromRawBytes
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     cruxic_aware_GLImage
 * Method:    allocateBlank
 * Signature: (IIB)Lcruxic/aware/GLImage;
 */
JNIEXPORT jobject JNICALL Java_cruxic_aware_GLImage_allocateBlank
  (JNIEnv *, jclass, jint, jint, jbyte);

/*
 * Class:     cruxic_aware_GLImage
 * Method:    copyRect
 * Signature: (Lcruxic/aware/GLImage;IIII)V
 */
JNIEXPORT void JNICALL Java_cruxic_aware_GLImage_copyRect
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     cruxic_aware_GLImage
 * Method:    fillRect
 * Signature: (IIIIBBB)V
 */
JNIEXPORT void JNICALL Java_cruxic_aware_GLImage_fillRect
  (JNIEnv *, jobject, jint, jint, jint, jint, jbyte, jbyte, jbyte);

/*
 * Class:     cruxic_aware_GLImage
 * Method:    combine
 * Signature: (Lcruxic/aware/GLImage;IIII)V
 */
JNIEXPORT void JNICALL Java_cruxic_aware_GLImage_combine
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
