/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cruxic_aware_overlays_Liquid_StaticNoiseOverlay_Impl */

#ifndef _Included_cruxic_aware_overlays_Liquid_StaticNoiseOverlay_Impl
#define _Included_cruxic_aware_overlays_Liquid_StaticNoiseOverlay_Impl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cruxic_aware_overlays_Liquid_StaticNoiseOverlay_Impl
 * Method:    init
 * Signature: (Lcruxic/aware/GLImage;Lcruxic/aware/GLImage;FF)I
 */
JNIEXPORT jint JNICALL Java_cruxic_aware_overlays_Liquid_1StaticNoiseOverlay_1Impl_init
  (JNIEnv *, jobject, jobject, jobject, jfloat, jfloat);

/*
 * Class:     cruxic_aware_overlays_Liquid_StaticNoiseOverlay_Impl
 * Method:    update
 * Signature: (IFLcruxic/aware/GLImage;II)V
 */
JNIEXPORT void JNICALL Java_cruxic_aware_overlays_Liquid_1StaticNoiseOverlay_1Impl_update
  (JNIEnv *, jobject, jint, jfloat, jobject, jint, jint);

/*
 * Class:     cruxic_aware_overlays_Liquid_StaticNoiseOverlay_Impl
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cruxic_aware_overlays_Liquid_1StaticNoiseOverlay_1Impl_dispose
  (JNIEnv *, jobject);

/*
 * Class:     cruxic_aware_overlays_Liquid_StaticNoiseOverlay_Impl
 * Method:    getRect
 * Signature: (I)Lcruxic/math/Rect4i;
 */
JNIEXPORT jobject JNICALL Java_cruxic_aware_overlays_Liquid_1StaticNoiseOverlay_1Impl_getRect
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
